// app/lib/specialtyIcons.ts
// Maps the icon name stored in specialties-detail.json to the actual Hugeicons icon.
// Add new entries here whenever a new specialty/icon is introduced in the data file.

import {
  BoneIcon,
  BrainIcon,
  AmbulanceIcon,
  RibbonIcon,
  StethoscopeIcon,
  MicroscopeIcon,
  ScissorsIcon,
  DropletIcon,
  XRayIcon,
  MedicalFileIcon,
  FavouriteIcon,
  KidneysIcon,
  LungsIcon,
  Baby01Icon,
  TestTubeIcon,
  BloodIcon,
  HospitalIcon,
  Building01Icon,
  AlertCircleIcon,
  HealthIcon,
  WheelchairIcon,
  ShieldCheckIcon,
  UserIcon,
  ActivityIcon,
  PotionIcon,
  Home01Icon,
  EyeIcon,
  Bug01Icon,
  RefreshIcon,
  UserGroupIcon,
  HouseHeartIcon,
  HeartCheckIcon,
  PillIcon,
  FlashIcon,
  BandageIcon,
  SparklesIcon,
  FileTextIcon,
  UserCheckIcon,
} from '@hugeicons/core-free-icons';

export const specialtyIconMap: Record<string, typeof BoneIcon> = {
  BoneIcon,
  BrainIcon,
  AmbulanceIcon,
  RibbonIcon,
  StethoscopeIcon,
  MicroscopeIcon,
  ScissorsIcon,
  DropletIcon,
  XRayIcon,
  MedicalFileIcon,
  FavouriteIcon,
  KidneysIcon,
  LungsIcon,
  Baby01Icon,
  TestTubeIcon,
  BloodIcon,
  HospitalIcon,
  Building01Icon,
  AlertCircleIcon,
  HealthIcon,
  WheelchairIcon,
  ShieldCheckIcon,
  UserIcon,
  ActivityIcon,
  PotionIcon,
  Home01Icon,
  EyeIcon,
  Bug01Icon,
  RefreshIcon,
  UserGroupIcon,
  HouseHeartIcon,
  HeartCheckIcon,
  PillIcon,
  FlashIcon,
  BandageIcon,
  SparklesIcon,
  FileTextIcon,
  UserCheckIcon,
};

export function getSpecialtyIcon(name: string) {
  return specialtyIconMap[name] ?? StethoscopeIcon;
}